### ISSUE TITLE
Add WebDAV synchronization

### ISSUE THREAD

**Issue by holton-jiang** [quillpad/quillpad#124]
Because most people's most common synchronization method is WebDAV.

**Comment by jsixface** [comment]
I've been working on something similar. To sync it to a file system. This file system can be local or a remote file system like nextcloud/ pcloud.

**Comment by tangshg** [comment]
> I've been working on something similar. To sync it to a file system. This file system can be local or a remote file system like nextcloud/ pcloud. 

I hope you can add webdav service, thank you very much

**Comment by LasmGratel** [comment]
Is this still being worked on?

**Comment by wu4339** [comment]
+1

**Comment by aer0nix** [comment]
+1

**Comment by opk12** [comment]
The file system is not a replacement: I'm not comfortable with the notes being visible to the proprietary spyw-- apps that I need from the Play Store (chat, bank, child's school, municipality). The notes should be in the app's private directory and synchronized on the network.

**Comment by tangshg** [comment]
![image](https://github.com/quillpad/quillpad/assets/37105296/24812bfd-2517-4d68-b900-f02e90089cad)
I am adding the webdav service and my work is very busy. I have very little time, so it will take some more time

**Comment by azertylr** [comment]
hello,

it would be awesome to have sync with ownCloud oCIS (using webdav with ODIC!)

thanks!

**Comment by lguenth** [comment]
Would love this as well! Nextcloud can be quite heavy if you don't use it for anything else, so a more general WebDAV solution would be great.

Hey @tangshg, thanks for trying to implement this! I saw in your fork that you had to stop developing this further. Can you give a brief overview of what is already working in your version and what still needs to be done?

**Comment by tangshg** [comment]
> Would love this as well! Nextcloud can be quite heavy if you don't use it for anything else, so a more general WebDAV solution would be great.
> 
> Hey @tangshg, thanks for trying to implement this! I saw in your fork that you had to stop developing this further. Can you give a brief overview of what is already working in your version and what still needs to be done?

I had to stop adding webdav because the original author was still updating the data storage schema, and I had to wait for the author to finish. In order to work further

**Comment by err0r2k** [comment]
WebDAV Support would be great!

**Comment by jsixface** [comment]
WebDAV not planned as is. If you have DAVx5 app, you can configure the WebDAV share there and use the "FileSystem" sync feature in Quillpad to sync to the webDav folder.

**Comment by petrm** [comment]
Thanks for the hint with DAVx5. I set this up, but I always end up with zero byte files and as soon as I fill the file with other source, it gets wiped by quillpad again. Is there a log I could check?

**Comment by jsixface** [comment]
I am looking into the zero byte thing. You can check the logs via adb or can send a app log report in the "About" section.

**Comment by petrm** [comment]
I didn't find the option to send logs in the about section (f-droid build), but I checked logcat. The files get created with correct names, but are always empty.

```
getAll: Error listing files
java.io.IOException: read failed: EIO (I/O error)
	at libcore.io.IoBridge.read(IoBridge.java:614)
	at java.io.FileInputStream.read(FileInputStream.java:353)
	at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:1074)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
	at java.io.InputStreamReader.read(InputStreamReader.java:177)
	at java.io.BufferedReader.read1(BufferedReader.java:221)
	at java.io.BufferedReader.read(BufferedReader.java:298)
	at java.io.Reader.read(Reader.java:229)
	at A7.c.Q(SourceFile:10)
	at Y7.b.f(SourceFile:69)
	at Y7.b.b(SourceFile:242)
	at V7.p.r(SourceFile:252)
	at V7.m.p(SourceFile:12)
	at E5.a.o(SourceFile:9)
	at Z5.F.run(SourceFile:107)
	at F2.a.a(SourceFile:6)
	at F2.a.run(SourceFile:563)
	at g6.j.run(SourceFile:3)
	at g6.a.run(SourceFile:88)
Caused by: android.system.ErrnoException: read failed: EIO (I/O error)
	at libcore.io.Linux.readBytes(Native Method)
	at libcore.io.Linux.read(Linux.java:229)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:618)
	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:325)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:618)
	at libcore.io.IoBridge.read(IoBridge.java:604)
	at java.io.FileInputStream.read(FileInputStream.java:353) 
	at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:1074) 
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291) 
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355) 
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181) 
	at java.io.InputStreamReader.read(InputStreamReader.java:177) 
	at java.io.BufferedReader.read1(BufferedReader.java:221) 
	at java.io.BufferedReader.read(BufferedReader.java:298) 
	at java.io.Reader.read(Reader.java:229) 
	at A7.c.Q(SourceFile:10) 
	at Y7.b.f(SourceFile:69) 
	at Y7.b.b(SourceFile:242) 
	at V7.p.r(SourceFile:252) 
	at V7.m.p(SourceFile:12) 
	at E5.a.o(SourceFile:9) 
	at Z5.F.run(SourceFile:107) 
	at F2.a.a(SourceFile:6) 
	at F2.a.run(SourceFile:563) 
	at g6.j.run(SourceFile:3) 
	at g6.a.run(SourceFile:88) 
```

**Comment by petrm** [comment]
I started to debug this a bit. I am using sftpgo as the webdav server.

I checked that something like https://github.com/bitfireAT/davx5-ose/discussions/326 or https://github.com/bitfireAT/davx5-ose/discussions/1419 does not apply. I am able to upload files to the server fine.

When I swipe to refresh in quillpad, I see in my server log:

```
{
   "level":"info",
   "time":"2025-10-07T13:31:26.860",
   "sender":"webdavd",
   "content_length":"0",
   "elapsed_ms":0,
   "method":"PUT",
   "proto":"HTTP/1.1",
   "remote_addr":"172.21.0.49:36328",
   "request_id":"d3ifk3mung1000epahr0",
   "resp_status":201,
   "uri":"http://REDACTED/md-notes-sync/How%20should%20I%20sync%3F.md",
   "user_agent":"DAVx5/4.5.4-ose (dav4jvm; okhttp/5.1.0) Android/15"
}
```
Not clear to me if this is a bug in the implementation of davx5 mount or quillpad.
